/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\mascot.glb --types 
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React, { useEffect } from "react";
import * as THREE from "three";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "Armature|mixamo.com|Layer0" | "Armature|mixamo.com|Layer0.001";

interface GLTFAction extends THREE.AnimationClip {
        name: ActionName;
}

type GLTFResult = GLTF & {
        nodes: {
                mesh_char_129_1: THREE.SkinnedMesh;
                mixamorigHips: THREE.Bone;
        };
        materials: {
                ["_023_CarrotKind.001"]: THREE.MeshStandardMaterial;
        };
        animations: GLTFAction[];
};

export function MascotModel({ state }: { state: "dance" | "crawl" }) {
        const group = React.useRef<THREE.Group>();
        const { scene, animations } = useGLTF("/mascot.glb");
        const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
        const { nodes, materials } = useGraph(clone) as GLTFResult;
        const { actions } = useAnimations(animations, group);
        useEffect(() => {
                if (state === "dance") {
                        actions["Armature|mixamo.com|Layer0.001"]?.play();
                        actions["Armature|mixamo.com|Layer0"]?.stop();
                } else if (state === "crawl") {
                        actions["Armature|mixamo.com|Layer0"]?.play();
                        actions["Armature|mixamo.com|Layer0.001"]?.stop();
                }
        }, [state, actions]);
        return (
                <group ref={group} dispose={null}>
                        <group name="Scene">
                                <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
                                        <primitive object={nodes.mixamorigHips} />
                                        <skinnedMesh
                                                name="mesh_char_129_1"
                                                geometry={nodes.mesh_char_129_1.geometry}
                                                material={materials["_023_CarrotKind.001"]}
                                                skeleton={nodes.mesh_char_129_1.skeleton}
                                                morphTargetDictionary={
                                                        nodes.mesh_char_129_1.morphTargetDictionary
                                                }
                                                morphTargetInfluences={
                                                        nodes.mesh_char_129_1.morphTargetInfluences
                                                }
                                        />
                                </group>
                        </group>
                </group>
        );
}

useGLTF.preload("/mascot.glb");
